import type { Metadata } from "next";
import { Inter, Saira, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});
const saira = Saira(
  {
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-saira",
  },
);
const manrope = Manrope(
  {
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-saira",
  },
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saira.variable} ${inter.variable} ${manrope.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
